auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: mahongquan
url: http://mahongquan.github.io
feed: /atom.xml
author_info: <a href="http://mahongquan.github.io/">BeiYuu</a>
